### ISSUE TITLE
Version 0.0.4.5, ValueError: '辛' is not in list

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#20]
Happy new year to you, Mr. Tang!

Thank you for the update of kinqimen.

I've just updated it to kinqimen 0.0.4.5, when running for 2022, Feb , 7th, 11 o'clock, it pops error:

    Traceback (most recent call last):
    File "C:\My Documents\Scripts\Qimen 1.py", line 179, in <module>
    qimen = kinqimen.Qimen(2022,2,7,11).pan()
    File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 209, in pan
    return {"干支":self.gangzhi()[0]+"年"+self.gangzhi()[1]+"月"+self.gangzhi()[2]+"日"+self.gangzhi()[3]+"時","旬首":self.shun(self.gangzhi()[2]),"旬空":self.daykong_shikong(),"局日":self.qimen_ju_day(), "排局":self.qimen_ju_name(), "節氣":self.find_jieqi(), "值符值使":self.zhifu_n_zhishi(), "天乙":self.tianyi(), "天盤":self.pan_sky(), "地盤":self.pan_earth()[0], "門":self.pan_door(),"星":self.pan_star()[0], "神":self.pan_god(), "馬星": {"天馬": self.moonhorse(),"丁馬":self.dinhorse(), "驛馬":self.hourhorse()}, "長生運": self.gong_chengsun()}
    File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 107, in pan_sky
    gan_reorder = new_list([self.pan_earth()[0].get(i) for i in list(rotate)], fu_head)
    File "C:\Python38\lib\site-packages\kinqimen\config.py", line 26, in new_list
    zhihead_code = olist.index(o)
    ValueError: '辛' is not in list`

Can you please have a look? Thank you!

**Comment by kentang2017** [comment]
fixed & please try again

**Comment by P-Rainbow** [comment]
thanks! Mr. Tang @kentang2017 , but with the version 0.0.4.6, it pops:

    Traceback (most recent call last):
    File "C:\My Documents\Scripts\Qimen 1.py", line 179, in <module>
    qimen = kinqimen.Qimen(2022,2,7,9).pan()
    File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 17, in __init__
    self.g = self.gpan()
    File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 242, in gpan
    dgz = self.gangzhi()[2]
    File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 45, in gangzhi
    cdate = sxtwl.fromSolar(self.year, self.month, self.day)
    AttributeError: module 'sxtwl' has no attribute 'fromSolar'

**Comment by kentang2017** [comment]
please upgrade sxtwl

**Comment by P-Rainbow** [comment]
@kentang2017 , brilliant, Mr. Tang. problem perfectly solved! :)
