### ISSUE TITLE
Version 0.0.5.0, ModuleNotFoundError: No module named 'ephem'

### ISSUE THREAD

**Issue by P-Rainbow** [kentang2017/kinqimen#24]
Good day Mr. Tang,

When upgraded to kinqimen 0.0.5.0, running the program it pops an error says "ModuleNotFoundError: No module named 'ephem'" .

Can you please have a look? Thank you.

    Traceback (most recent call last):
      File "C:\My Documents\Qimen.py", line 1, in <module>
        from kinqimen import kinqimen
      File "C:\Python38\lib\site-packages\kinqimen\kinqimen.py", line 6, in <module>
        from kinqimen.config import *
      File "C:\Python38\lib\site-packages\kinqimen\config.py", line 8, in <module>
        from ephem import *
    ModuleNotFoundError: No module named 'ephem'

**Comment by kentang2017** [comment]
pip install ephem, i have embed one more package

**Comment by P-Rainbow** [comment]
Thank you! Case closed. :）
