### ISSUE TITLE
ModuleNotFoundError: No module named 'config' Python3

### ISSUE THREAD

**Issue by jebberwocky** [kentang2017/kinqimen#39]
Python version: Python 3.11.4

test code:
`
from kinqimen import kinqimen
kinqimen.Qimen(2024, 3, 27, 16,50).pan()
`

error:
`
Traceback (most recent call last):
  File "/Users/jeff/Documents/GitHub/qimendunjia/qmdj.py", line 1, in <module>
    from kinqimen.kinqimen import Qimen
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/kinqimen/kinqimen.py", line 9, in <module>
    import config
ModuleNotFoundError: No module named 'config'
`

看了下您的source code, 是引用了同个directory下的config.py. 请问是否不支持 Python3 

谢谢

**Comment by jebberwocky** [comment]
一个workaround的思路: 
copy kinqimen.py 和config.py到project directory. 当local file import即可

closing issue

**Comment by kentang2017** [comment]
是可以的，放在同一目錄內是可以執行的
